---
- name: "update apt packages"
  become: true
  become_method: sudo
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  become_method: sudo
  apt:
    upgrade: yes

- name: "Remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "install dependencies: NodeJS, NPM"
  become: true
  become_method: sudo
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  become_method: sudo
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create ~/web directory"
  file: 
    path: ~/web
    state: directory

- name: "copy index.js"
  template:
    src: "files/index.js"
    dest: "~/web/index.js"

- name: "starting server"
  shell: |
    pm2 start ~/web/index.js -f
